const data = {
    products: [
      {
        name: 'Sling Bag',
        slug: 'sling-bag',
        category: 'Bags',
        image: '/images/p1.jfif', // 679px × 829px
        price: 120,
        countInStock: 10,
        brand: 'Rains',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality bag',
      },
      {
        name: 'Hand Bag',
        slug: 'hand-bag',
        category: 'Bags',
        image: '/images/p2.jfif',
        price: 250,
        countInStock: 0,
        brand: 'Dior',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        name: 'Backpack',
        slug: 'backpack',
        category: 'Bags',
        image: '/images/p3.jfif',
        price: 25,
        countInStock: 15,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        name: 'Red Backpack',
        slug: 'red-backpack',
        category: 'Bags',
        image: '/images/p3.jfif',
        price: 25,
        countInStock: 15,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
    ],
  };
  export default data;